# Generated by Django 4.0.2 on 2022-03-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_alter_libro_options_alter_libro_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'libro', 'verbose_name_plural': 'libros'},
        ),
        migrations.AddField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('A', 'Adulto'), ('N', 'Niños')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(null=True, upload_to='libros/'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
